# Intro to NumPy

In [1]:
import numpy as np
import pandas as pd

## Datatypes & Attributes

In [2]:
# NumPy's main datatype is ND-Array
a1 = np.array([1,2,3])
type(a1)

numpy.ndarray

In [3]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [4]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
# Dimension
a3.shape

(2, 3, 3)

In [6]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [8]:
a1.dtype , type(a2)

(dtype('int32'), numpy.ndarray)

In [9]:
# Create a DataFrame from NumPy array
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [10]:
sample_array = np.array([1, 2, 3])
# New array of given shape all containing one
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# New array of given shape all containing zero
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Array of st to en with given gap
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [13]:
# Random array of given shape ranging from st to en
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[1, 0, 0, 8, 9],
       [6, 6, 5, 9, 2],
       [3, 3, 6, 6, 6]])

In [14]:
# Random array of given shape ranging from 0 to 1
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.5660526 , 0.48328256, 0.65554066],
       [0.88936732, 0.18896691, 0.66621344],
       [0.14757685, 0.86873359, 0.11343842],
       [0.50034296, 0.22166023, 0.85534537],
       [0.54269722, 0.10005205, 0.6250034 ]])

In [15]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.87010933, 0.76452382, 0.03814214],
       [0.23492799, 0.34316546, 0.25871561],
       [0.92944854, 0.28906316, 0.03412343],
       [0.71693336, 0.70833788, 0.93606787],
       [0.50210369, 0.13421767, 0.56285726]])

In [24]:
# Pseudo-random numbers -> Generates same random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(0,10,size=(3,5))
random_array_4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

## Viewing arrays and matrices

In [25]:
# Unique values
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [28]:
a4.shape, a4.ndim
# 5 = column
# 4 = row
# 3 = amount of matrices
# 2 = amount of copy

((2, 3, 4, 5), 4)

In [30]:
# Get first n numbers of the inner most arrays
a4[:,:,:,:3]

array([[[[6, 7, 7],
         [5, 9, 8],
         [3, 0, 3],
         [2, 3, 8]],

        [[3, 3, 7],
         [9, 9, 0],
         [3, 2, 7],
         [0, 4, 5]],

        [[8, 4, 1],
         [8, 1, 1],
         [9, 3, 6],
         [0, 3, 5]]],


       [[[4, 6, 4],
         [4, 4, 8],
         [7, 5, 5],
         [5, 9, 3]],

        [[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0],
         [2, 9, 2]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0],
         [0, 6, 3]]]])

## Manipulating & comparing arrays

### Arithmatic

In [31]:
a1

array([1, 2, 3])

In [32]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [34]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [37]:
# Float divison
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [38]:
# Integer divison
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [41]:
# Squaring matrices
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [42]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [43]:
# Exponential
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [44]:
# ln of arrays (log base e)
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [51]:
# Creating large NumPy Array
large_array = np.random.random(100000)
large_array[:10]

array([0.42767272, 0.78253307, 0.41163343, 0.6952434 , 0.76821854,
       0.19032022, 0.88584506, 0.98252442, 0.95018423, 0.166389  ])

In [53]:
%timeit sum(large_array) # Python sum time
%timeit np.sum(large_array) # NumPy sum time

9.31 ms ± 243 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
51.3 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
np.mean(a2)

3.6333333333333333

In [60]:
np.max(a2)

6.5

In [61]:
np.min(a2)

1.0

In [62]:
# Standard deviation
np.std(a2)

1.8226964152656422

In [63]:
# Varience
np.var(a2)
# sqrt(var)=std

3.3222222222222224

## Reshape and Transpose

In [68]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [69]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [70]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [75]:
a2_reshape = a2.reshape(2,3,1)

In [72]:
a3.shape

(2, 3, 3)

In [76]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [82]:
# Transpose
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a2.shape

(2, 3)

In [84]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [86]:
a2.T.shape

(3, 2)

## Dot Product

In [88]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [89]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [90]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [91]:
# Element wise multiplication
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [92]:
# Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [100]:
mat1 = mat1.T

In [101]:
mat1.shape, mat2.shape

((3, 5), (5, 3))

In [102]:
mat3 = np.dot(mat1,mat2)

In [103]:
mat3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

## Comparison Operators

In [104]:
a1

array([1, 2, 3])

In [105]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [108]:
a1 < a2

array([[False, False,  True],
       [ True,  True,  True]])

In [112]:
a1 <= 2

array([ True,  True, False])

In [111]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting arrays

In [113]:
random_array

array([[1, 0, 0, 8, 9],
       [6, 6, 5, 9, 2],
       [3, 3, 6, 6, 6]])

In [114]:
# Sort by rows
np.sort(random_array)

array([[0, 0, 1, 8, 9],
       [2, 5, 6, 6, 9],
       [3, 3, 6, 6, 6]])

In [115]:
# Indices of element of sorted array
np.argsort(random_array)

array([[1, 2, 0, 3, 4],
       [4, 2, 0, 1, 3],
       [0, 1, 2, 3, 4]], dtype=int64)

In [116]:
np.argmax(a2)

5

In [117]:
# Indices of max elements in sorted array of each rows
np.argmax(random_array,axis=1)

array([4, 3, 2], dtype=int64)